version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile  # Pointing to the root Dockerfile
    container_name: ratiod-backend
    environment:
      - PORT=3000
      - FRONTEND_URL=${FRONTEND_URL}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
    ports:
      - "3010:3000"
