version: "3.8"
services:
  backend:
    image: node:20-alpine
    container_name: ratiod-backend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/backend/node_modules
      - /app/apps/frontend/node_modules
    environment:
      - PORT=3000
      - FRONTEND_URL=${FRONTEND_URL}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install -g pnpm@10.15.1 &&
             pnpm install &&
             pnpm --filter backend run build &&
             pnpm --filter backend run start"
